name: Tile Drills
favicon: null
layout_spectrum: 0.44399230647832155
typography_spectrum: 0.1645688028074801
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.23905802983790636
  lightness: 0.10036608413793147
  saturation: 0.8911392458248883
  rhythmicContrast: 0.6197863125707954
purpose: []
