name: Tile Drills
favicon: null
layout_spectrum: 0.76207
typography_spectrum: 0.1645688028074801
title: TDB
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.6197863125707954
purpose: []
